import { Post } from "../model/post";
import axios from "axios";
import Link from "next/link";

export const metadata = {
  title: "Post Page",
  description: "Generated by create next app",
};

export default async function Page() {
  const { data } = await axios.get<Post[]>("http://localhost:3001/posts");

  return (
    <div>
      <h1 className="font-bold text-2xl text-gray-600">Post Page</h1>
      <div className="py-4 text-gray-600">
                {data.map((post) => (
                    <div key={post.id} className="p-4 my-3">
                      <Link href={`/posts/${post.id}`}>
                        <b>{post.title}</b>
                      </Link>
                      <p>{post.description}</p>
                    </div>
                ))}
            </div>
    </div>
  );
}
