import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./partials/Sidebar";
import Content from "./partials/Content";
import Footer from "./partials/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex w-full h-screen">
          <Sidebar />
          <div className="right-container p-4 w-[78%] overflow-y-scroll">
            <Content>{children}</Content>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
